### ISSUE TITLE
No example or code for BasicAuthentication

### ISSUE THREAD

**Issue by dbeletsis** [SolrNet/SolrNet#402]
Hi,

I cant find any reference on how i can set basic authentication credentials when initializing SolrNet in a asp.net core 2.0 project.

I am using SolrNet,Microsoft DependencyInjection package with the following code in Starup.cs

services.AddSolrNet("http://localhost:81/solr");

Please help!
With regards,
Dimitris

**Comment by gjunge** [comment]
I think we will have to add support for it in the form of an overload to AddSolrNet. I’ll try to free some time  next week to get that functionality in.

**Comment by dbeletsis** [comment]
That will be perfect! Thank you so much - keep up the good work!

**Comment by gjunge** [comment]
In the next release, 1.0.8 (somewhere this week I guess), you can now control the HttpClient during service configuration.
See https://github.com/SolrNet/SolrNet/blob/master/Microsoft.DependencyInjection.SolrNet.Tests/MicrosoftDependencyFixture.cs#L112 for an example on how to set basic Authentication headers.

**Comment by xavier-morera** [comment]
@gjunge should I release 1.0.8?

**Comment by gjunge** [comment]
I want to see if we can get #407 in as well.

**Comment by dbeletsis** [comment]
Hi again!

I just downloaded the updated SolrNet Nuget package (1.0.8), i used the new AddSolrNet overload EXACTLY as described on the example above, but when i try to connect to Solr, i get a "The remote server returned an error: (401) Unauthorized."

Any ideas? Thank you!

**Comment by gjunge** [comment]
Can you check with Fiddler if SolrNet is sending the right headers, and check if they are the same headers as you sent when using your browser.

**Comment by dbeletsis** [comment]
Hi @gjunge , thank you for the reply!

Here are the results of my investigation:

1. In my `startup.cs` i configure SolrNet, with this code:
```
var credentials = System.Text.Encoding.ASCII.GetBytes("myUsername:myPassword");
var credentialsBase64 = Convert.ToBase64String(credentials);
services.AddSolrNet("http://localhost.fiddler:81/solr/myCoreName", options =>
 {
    options.HttpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", credentialsBase64);
});
```
(I use ".**fiddler**" in my url, just for debug purposes)

Then, in my SearchController constructor, i inject Solr like this:

```
private readonly ISolrBasicOperations<Document> Solr;

public SearchController(ISolrBasicOperations<Document> solr)
{
    Solr = solr;
}
```
Up to this point, everything seems ok, because when i debug the **solr** object, i can see that the "`solr -> connection -> HttpClient -> DefaultRequestHeaders -> Authorization` has a valid value: `"{Basic ZGltaZRyaXM6NTIzNA==}"`, exactly the same as the **credentialsBase64** var in my `startup.cs`

But, when i execute a query, i get a **401 response** and fiddler shows that **no** Authorization Header is set!

Hope that this helps!
Have a nice day!

**Comment by gjunge** [comment]
I just tested it, and I do get the Authentication header in Fiddler.

How are you executing the queries? Are you using `Query` or `QueryAsync` ?

**Comment by dbeletsis** [comment]
Hi again, sorry for the late reply - i was out of town...

Well, seems that you found the solution: I was using `Query` but when i switched to `QueryAsync`, everything worked just fine!

It seems, that the **non async** function needs a fix! 

Thank you for the support!

**Comment by gjunge** [comment]
It is kind of a known issue, the AutoSolrConnection uses the new HttpClient for Async only (since HttpClient is Async only), and falls back to the old SolrPostConnection  for Sync calls.

Perhaps we should make AutoSolrConnection include a setting whether to allow Sync calls, and have that turned off by default in the SolrNet.Microsoft.DependencyInjection package.

**Comment by mde-coder** [comment]
Hi, is this issue solved in the latest version? I tried to use Basic Authentication in combination with AutoSolrConnection. When I launch a Query I get 'Unauthorized'. When I use the same credentials with SolrConnection, everything works fine.

`Startup.InitContainer();
var sc = new ServiceCollection();

//my credentials
var credentials = System.Text.Encoding.ASCII.GetBytes(SolrUserName + ":" + SolrPassword);

//in base64
var credentialsBase64 = Convert.ToBase64String(credentials);

//use the options to set the Authorization header.
sc.AddSolrNet<string>(solrAppUrl, options => { options.HttpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", credentialsBase64); });

//test
var provider = sc.BuildServiceProvider();
var injectionConnection = provider.GetRequiredService<ISolrInjectedConnection<string>>() as BasicInjectionConnection<string>;
var connection = injectionConnection.Connection as AutoSolrConnection;

Startup.Init<SolrResult>(connection);`

**Comment by fatihyildizhan** [comment]
Is there any solution yet?

I am still getting `"The remote server returned an error: (401) Unauthorized."`.

Thanks

**Comment by mausch** [comment]
@fatihyildizhan Hi, have you tried the async methods, as mentioned above?

**Comment by fatihyildizhan** [comment]
Hi,

I compiled the answers above and created a simple .NET 5 project. You may check the Readme as well.

https://github.com/bau-global/SolrNET5WebAPI

- Startup
```
var credentials = Encoding.ASCII.GetBytes("username:password");
var credentialsBase64 = Convert.ToBase64String(credentials);
services.AddSolrNet<WeatherForecast>("https://solr-server-ip:port/solr/name", options =>
{
  options.HttpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", credentialsBase64);
});
```

- Controller
`SolrQueryResults<WeatherForecast> results = await _solr.QueryAsync(new SolrQuery($"summary: {parameter}"));`

**Comment by jevgenigeurtsencolours** [comment]
To fix the usage of sync calls we needed to patch some SolrNet code to actually use `BasicAuthHttpWebRequestFactory` instead of the hardcoded `HttpWebRequestFactory`:

```
        /// <summary>
        /// For sync calls <see cref="AutoSolrConnection"/> falls back to <see cref="PostSolrConnection"/>. 
        /// The creation is handled inside <see cref="AutoSolrConnection(string, HttpClient)"/> and cannot be intercepted/modified.
        /// 
        /// Patch 1:
        /// <see cref="AutoSolrConnection(string, HttpClient)"/> creates an inline instance of <see cref="SolrConnection"/> that contains a 'hardcoded' constraint on <see cref="HttpWebRequestFactory"/>.
        /// This inline instance gets passed into <see cref="PostSolrConnection(ISolrConnection, string)"/>
        /// 
        /// We need to obtain the instance of <see cref="PostSolrConnection"/> and modify the private field that was passed through the constructor.
        /// 
        /// Patch 2:
        /// Whenever a <see cref="PostSolrConnection"/> instance is created, <see cref="PostSolrConnection(ISolrConnection, string)"/>  also contains a 'hardcoded' constraint on <see cref="HttpWebRequestFactory"/>
        /// 
        /// This method uses reflection to find both <see cref="PostSolrConnection.HttpWebRequestFactory"/> fields and sets it to use <see cref="BasicAuthHttpWebRequestFactory"/> using the passed <paramref name="solrCredentials"/>.
        /// </summary>
        private static void SetBasicAuthInAutoSolrConnection(AutoSolrConnection autoSolrConnection, NetworkCredential solrCredentials)
        {
            if (autoSolrConnection != null)
            {
                var basicAuthFactory = new BasicAuthHttpWebRequestFactory(solrCredentials.UserName, solrCredentials.Password);

                // get PostSolrConnection property reference from AutoSolrConnection
                var syncFallbackConnectionProperty = autoSolrConnection.GetType().GetProperty("SyncFallbackConnection", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);

                // get actual PostSolrConnection instance from AutoSolrConnection
                var postSolrConnection = syncFallbackConnectionProperty.GetValue(autoSolrConnection);

                SetBasicAuthHttpWebRequestFactory(postSolrConnection, basicAuthFactory);

                // get conn property reference from PostSolrConnection
                var connProperty = postSolrConnection.GetType().GetField("conn", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);

                // get actual SolrConnection instance from PostSolrConnection
                var solrConnection = connProperty.GetValue(postSolrConnection);

                SetBasicAuthHttpWebRequestFactory(solrConnection, basicAuthFactory);
            }
        }

        private static void SetBasicAuthHttpWebRequestFactory(object instance, BasicAuthHttpWebRequestFactory basicAuthHttpWebRequestFactory)
        {
            // get HttpWebRequestFactory property reference from PostSolrConnection
            var httpWebRequestFactoryProperty = instance.GetType().GetProperty("HttpWebRequestFactory", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public);

            // set BasicAuthHttpWebRequestFactory on instance
            httpWebRequestFactoryProperty.SetValue(instance, basicAuthHttpWebRequestFactory);
        }
```

And use it like this whenever we create a `AutoSolrConnection`:

```
        private static ISolrConnection CreateAutoSolrConnection(string solrUrl, Action<SolrNetOptions> setupAction, NetworkCredential solrCredentials)
        {
            if (string.IsNullOrWhiteSpace(solrUrl)) throw new ArgumentNullException(nameof(solrUrl));

            // deviation from documentation code: make sure AutoSolrConnection uses our HttpClientHandler with credentials.
            var httpClientHandler = new HttpClientHandler
            {
                AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip,
                Credentials = solrCredentials
            };

            var httpClient = new HttpClient(httpClientHandler);

            var connection = new AutoSolrConnection(solrUrl, httpClient);

            // deviation from documentation code: make sure AutoSolrConnection internals use BasicAuthHttpWebRequestFactory
            SetBasicAuthInAutoSolrConnection(connection, solrCredentials);

            if (setupAction == null) return connection;

            // Allow for custom headers to be injected.
            var options = new SolrNetOptions(connection.HttpClient);
            setupAction(options);
            return connection;
        }
```

I'll create a PR that allows us to have more control over the type of factory in code asap.

**Comment by jevgenigeurtsen** [comment]
Created PR: https://github.com/SolrNet/SolrNet/pull/583
